import { motion } from 'framer-motion';
import { FiFileText } from 'react-icons/fi';

const Terms = () => {
    return (
        <div className="section-padding min-h-screen">
            <div className="container mx-auto px-6 max-w-4xl">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="text-center mb-12"
                >
                    <div className="inline-flex p-4 bg-[var(--primary)]/10 text-[var(--primary)] rounded-2xl mb-6 text-3xl">
                        <FiFileText />
                    </div>
                    <h1 className="text-4xl font-black mb-4">Terms of <span className="gradient-text">Service</span></h1>
                </motion.div>

                <div className="clean-card p-10 space-y-8 text-[var(--text-secondary)] font-medium leading-relaxed">
                    <section>
                        <h2 className="text-xl font-black text-[var(--text-main)] mb-4">1. Acceptance of Terms</h2>
                        <p>By using Garment House, you agree to comply with all production guidelines and payment terms specified during the order process.</p>
                    </section>
                    <section>
                        <h2 className="text-xl font-black text-[var(--text-main)] mb-4">2. Production & Quality</h2>
                        <p>While we strive for perfection, a standard production tolerance of ±5% in quantity and color shade is industry-standard and accepted.</p>
                    </section>
                    <section>
                        <h2 className="text-xl font-black text-[var(--text-main)] mb-4">3. Intellectual Property</h2>
                        <p>All designs provided by clients remain their intellectual property. Designs generated by our team are subject to separate agreements.</p>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default Terms;
